on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            runs-on: ubuntu-latest
            archive: zip
          - target: x86_64-unknown-linux-musl
            runs-on: ubuntu-latest
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            runs-on: macos-latest
            archive: zip
          - target: aarch64-apple-darwin
            runs-on: macos-latest
            archive: zip
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
