name: Build macOS (Apple Silicon)

on:
  release:
    types: [created]

jobs:
  release-macos-arm:
    name: Build macOS (Apple Silicon)
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust target for Apple Silicon
        run: rustup target add aarch64-apple-darwin

      - name: Get Release Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build macOS ARM64 binary
        run: cargo build --release --target aarch64-apple-darwin

      - name: Rename Binary with Version
        run: |
          mv target/aarch64-apple-darwin/release/moonshine-installer installer_${VERSION}_aarch64-apple-darwin
          zip installer_${VERSION}_aarch64-apple-darwin.zip installer_${VERSION}_aarch64-apple-darwin

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer_${{ env.VERSION }}_aarch64-apple-darwin.zip
          path: installer_${{ env.VERSION }}_aarch64-apple-darwin.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: installer_${{ env.VERSION }}_aarch64-apple-darwin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
