name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: moonshine-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: moonshine-windows.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: moonshine-macos

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename Binary
        run: mv target/${{ matrix.target }}/release/moonshine ${{ matrix.artifact }} || mv target/${{ matrix.target }}/release/moonshine.exe ${{ matrix.artifact }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
